version: '3.3'

services:
    traefik:
        image: traefik:v2.0.2
        container_name: traefik     
        hostname:       traefik       
        restart: always     
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
            - ./conf.d/:/etc/traefik/conf.d/
            - ./acme:/etc/traefik/acme
            # - ./cert/:/etc/traefik/ssl:ro            
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`${DOMAIN_NAME}`)"          
            - "traefik.http.routers.traefik.middlewares=https-only@file"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    
networks:
    default:
        external:
            name: app
