version: '3'

services:
    traefik:
        image: traefik:alpine
        command: --api --docker # Enables the web UI and tells Træfik to listen to docker
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/etc/traefik/traefik.toml:ro
            - ./.data/traefik/log/:/etc/traefik/log/

    portainer:
        image: portainer/portainer
        ports:
        - "9000:9000"
        command: -H unix:///var/run/docker.sock
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest
        environment:
          - MH_STORAGE=maildir
        volumes:
          - ./docker/mailhog/maildir:/maildir:rw,delegated
        ports:
          - "8025:8025"
          - "1025:1025"     
            

volumes:
  portainer_data:
    
networks:
    default:
        external:
            name: app
