version: '3.3'

services:
    traefik:
        image: traefik:v2.0.2
        container_name: ${PROJECT_NAME}     
        hostname:       ${PROJECT_NAME}       
        restart: always     
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
            - ./acme:/etc/traefik/acme
            - ./conf.d/:/etc/traefik/conf.d/
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik-api.rule=Host(`${DOMAIN_NAME}`)"
            - "traefik.http.routers.traefik-api.entrypoints=http"
            - "traefik.http.routers.traefik-api.middlewares=redirect@file"
            - "traefik.http.routers.traefik-api-s.rule=Host(`${DOMAIN_NAME}`)"
            - "traefik.http.routers.traefik-api-s.entrypoints=https"
            - "traefik.http.routers.traefik-api-s.tls.certresolver=le"
            - "traefik.http.services.traefik-api.loadbalancer.server.port=8080"     
networks:
    default:
        external:
            name: app
