version: '3.3'

services:
    traefik:
        image: traefik:v2.1.6
        container_name: ${PROJECT_NAME}
        hostname:       ${PROJECT_NAME}
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
            - ./conf.d/:/etc/traefik/conf.d/
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN_NAME}`)"
            - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=8080" 
    portainer:
        image: portainer/portainer
        ports:
        - "9000:9000"
        command: -H unix:///var/run/docker.sock
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest
        environment:
          - MH_STORAGE=maildir
        volumes:
          - ./docker/mailhog/maildir:/maildir:rw,delegated
        ports:
          - "8025:8025"
          - "1025:1025"

volumes:
    portainer_data:

networks:
    default:
        external:
            name: app
