[global]
  sendAnonymousUsage = false

[api]
  insecure = true

[entrypoints]
  [entrypoints.web]
    address = ":80"

  [entrypoints.web-secure]
    address = ":443"

[log]    
  level = "DEBUG"

[providers]
  [providers.docker]
    # Connection to docker host system (docker.sock)
    endpoint = "unix:///var/run/docker.sock"
    # This will hide all docker containers that don't have explicitly  
    # set label to "enable"
    exposedbydefault = false
    watch = true
  [providers.file]
      directory = "/etc/traefik/config.d"
      watch = true