################################################################
# Global configuration
################################################################

debug = false
checkNewVersion = true
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

################################################################
# Entry-points configuration
################################################################
[entryPoints]
  [entryPoints.http]
    address = ":80"

[traefikLog]
filePath = "/var/log/traefik/error.log"

[accessLog]
filePath = "/var/log/traefik/access.log"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]
address = ":8080"

################################################################
# Docker configuration backend
################################################################

[docker]
domain = "docker.localhost"
watch = true
exposedbydefault = false
endpoint = "unix:///var/run/docker.sock"
