################################################################
# Global configuration
################################################################

debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["http", "https","ws","wss"]

InsecureSkipVerify = true

[entryPoints]
    [entryPoints.http]
    address = ":80"

    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]

[traefikLog]
filePath = "log/error.log"

[accessLog]
filePath = "log/access.log"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]
address = ":8080"

################################################################
# Docker configuration backend
################################################################

[docker]
domain = "example.com"
