global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  web-secure: 
    address: ":443"
  traefik:
    address: ":8080"

metrics:
  prometheus: {}

# static configuration
log:
  level: DEBUG
  filePath: /tmp/traefik.log
  format: common

accessLog: {}

certificatesResolvers:
  le:
    acme:
      email: webmaster@uva3.com
      storage: "/etc/traefik/acme/acme.json"
      #If you uncommented the 'caserver' line, 
      #you will get an SSL error, but if you display the certificate 
      #and see it was emitted by Fake LE Intermediate X1 then it means 
      #all is good.
      #(It is the staging environment intermediate certificate used by let's encrypt).
      #You can now safely comment the acme.caserver line, remove the letsencrypt/acme.json
      #file and restart Traefik to issue a valid certificate.
      #***
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      #***
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedbydefault: false
    watch: true

  file:
    directory: /etc/traefik/conf.d/
    watch: true