global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    # http:
    #   middlewares:
    #     # - traefik-block-ua@file
    # #     - traefik-plugin-fail2ban@file
    #     - traefik-plugin-blockuseragent@file
  https:
    address: ":443"
    # http:
    #   middlewares:
    #     - traefik-plugin-fail2ban@file
    #     - traefik-plugin-blockuseragent@file
  traefik:
    address: ":8080"

metrics:
  prometheus: {}

# static configuration
log:
  level: DEBUG
  filePath: /tmp/traefik.log
  format: common

# Limiting the Logs to Specific Fields
# accessLog:
#   filePath: /tmp/access.log
#   format: json
#   fields:
#     defaultMode: keep
#     names:
#       ClientUsername: drop
#     headers:
#       defaultMode: keep
#       names:
#         User-Agent: keep
#         Authorization: drop
#         Content-Type: keep

providers:
  docker:
    # endpoint: "unix:///var/run/docker.sock"
    endpoint: "tcp://dockerproxy:2375"
    network: "traefik"
    exposedbydefault: false
    watch: true

  file:
    directory: /etc/traefik/conf.d/
    watch: true

# experimental:
#   plugins:
#     traefik-plugin-fail2ban:
#       moduleName: "github.com/juitde/traefik-plugin-fail2ban"
#       version: "v0.2.0"
#     traefik-plugin-blockuseragent:
#       moduleName: "github.com/agence-gaya/traefik-plugin-blockuseragent"
#       version: "v0.1.7"
#     traefik-block-ua:
#       moduleName: "github.com/kucjac/traefik-block-ua"
#       version: "v0.1.0"