apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceName: Tempo
          matcherRegex: "trace_id[\"\\s]*(?:=>|:|=)[\"\\s]*([a-f0-9]{32})"
          name: TraceID
          url: "/explore?schemaVersion=1&panes=%7B%22A%22:%7B%22datasource%22:%22Tempo%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22query%22:%22$${__value.raw}%22,%22queryType%22:%22traceql%22%7D%5D%7D%7D"
          urlDisplayLabel: "View Trace"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: Loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceName: Prometheus
      search:
        hide: false